### ISSUE TITLE
This line generates NPE if org is set to null in the while loop just above this line.

### ISSUE THREAD

**Issue by ghansham** [Unidata/thredds#929] opened 2017-10-03 10:12 UTC
https://github.com/Unidata/thredds/blob/a05e9fc00ac3ac7fab215c3db053fada57678675/cdm/src/main/java/ucar/nc2/dataset/VariableDS.java#L280

**Comment by ghansham** [comment] 2017-10-03 22:32
This is specific to NcML only.

**Comment by DennisHeimbigner** [comment] 2017-10-05 17:42
Do we have a test program for this so I can see if pull request
https://github.com/Unidata/thredds/pull/930
also fixes this.

**Comment by ghansham** [comment] 2017-10-05 18:38
I have a fix for that within variableDS class. But that may be a temporary fix. But still I will share it with you

**Comment by ghansham** [comment] 2017-10-06 02:29
The variables were unsigned short variables

**Comment by cwardgar** [comment] 2017-10-11 22:32
I was able to recreate this on 5.0.0 with the following NcML:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ncml:netcdf xmlns:ncml="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" enhance="all">
    <ncml:variable name="my_var" shape="" type="ushort">
        <ncml:attribute name="long_name" value="my_var_name" />
        <ncml:attribute name="_FillValue" type="ushort" value="65535" />
    </ncml:variable>
</ncml:netcdf>
```
The fix seems pretty straightforward.

**Comment by ghansham** [comment] 2017-10-12 01:50
What happens if my data is 10 bit and my fillvalue is 0. And I have another
variable where fillvalue is 1023. And I hv this fillvalue defined along
with variable as per CF conventions.

Regards
Ghansham

**Comment by DennisHeimbigner** [comment] 2017-10-12 03:06
Ghansham- Can you give specific ncml for your 10bit example?

**Comment by ghansham** [comment] 2017-10-12 03:10
Sure..i will send ncml and data as well.
Although I have not checked the behavior after the recent commits.

**Comment by DennisHeimbigner** [comment] 2017-10-12 03:11
The proximate cause is at VariableDS line 2803:
> needUnsignedConversion = (this.getDataType().isUnsigned() && !org.getDataType().isUnsigned());
this generates NPE because 'org' is null.
However, this occurs because of the code at  NcMLReader line 1218
> v = new VariableDS(ds, g, parentS, name, dtype, shape, null, null);
This seems incorrect to me. Instead, we should be creating an instance of Variable
instead of VariableDS.

**Comment by cwardgar** [comment] 2017-10-12 05:01
I already have a fix for this:
```java
    // do we need to do unsigned conversion ?
    Variable ultimateOrigVar = this;
    while (ultimateOrigVar instanceof VariableDS && ((VariableDS) ultimateOrigVar).getOriginalVariable() != null) {
      ultimateOrigVar = ((VariableDS) ultimateOrigVar).getOriginalVariable();
    }

    if (ultimateOrigVar == this) {
      needUnsignedConversion = false;
    } else {
      needUnsignedConversion = this.getDataType().isUnsigned() && !ultimateOrigVar.getDataType().isUnsigned();
    }
```
I'm going to wrap it into a larger commit that hopefully will fix all of these related unsigned issues. I'm focusing on 5.0.0 though. Dunno if I'll backport it.

**Comment by ghansham** [comment] 2017-10-12 06:07
I had a similar fix for this issue. I did it like this:

Variable org = this;
while(org instanceof VariableDS) {
             org= ( (VariableDS) org).getOriginalVariable();
}

if (org == null) { //This snipped was added by me. Rest of it is as it is.
         org=this;
}

needUnsignedCoversion = (this.getDataType().isUnsigned() &&
!org.getDataType().isUnsigned());

This fixed issue at my end.

**Comment by DennisHeimbigner** [comment] 2017-10-12 15:43
This is fine, but there is another issue here. I believe  that are other places in the code
that assume that  VariableDS.getOriginalVariable() is non-null. The NcMLReader code
breaks this assumption.

**Comment by ghansham** [comment] 2017-10-12 15:46
Can you send me list of possible test cases which are failing right now? I
will have a deeper look into the related classes. I will try to help.

**Comment by DennisHeimbigner** [comment] 2017-10-12 16:15
No suprisingly the relevant loop code in VariableDS  does not exist in master.
It was added as part of the wholesale introduction of unsigned types
into CDM.

**Comment by DennisHeimbigner** [comment] 2017-10-12 16:24
The problem is that the potential NPE problems are just that: potential. I would bet
that we do almost no testing of using ncml in this way. What we would need to
do is search for uses of VariableDS.getOriginalVariable() and see if they handle null.

**Comment by ghansham** [comment] 2017-10-12 17:45
One way to solve this problem could be to create a method for getting
origVar and use that method everywhere else. Even for unsignedness check,
similar approach can be followed. Then there will be one place from where
the bug can creep in for unsignedness.

Regards
Ghansham

**Closed** 2017-10-28 02:46 UTC

**Comment by ghansham** [comment] 2017-10-28 02:56
Thanks
