### ISSUE TITLE
WMS/Godiva2 issues in TDS 4.6.1

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#118] opened 2015-04-07 14:08 UTC
WMS is greatly enhanced in TDS 4.6, but there still seem to be a few lingering WMS/Godiva2 issues. 

I tried going to thredds.ucar.edu/thredds, which is at TDS 4.6.1:
![4-7-2015 9-48-38 am](https://cloud.githubusercontent.com/assets/1872600/7024836/8e1ff2c0-dd0d-11e4-996c-2ffad85ea309.png)

and I selected the 40km NAM, then selected `potential temperature @ fixed height above ground` and clicked `auto`.  There are three problems I identified:
* the grey spinning "working" indicator in the center of the plot never stops spinning.
* there is no "download in google earth" link
* if you zoom in or change the plot, the "download in google earth" link appears. 
* if you click `auto` again, you get no plot.

![4-7-2015 9-49-42 am](https://cloud.githubusercontent.com/assets/1872600/7024916/00996cc8-dd0e-11e4-8caa-54c224a650ad.png)

**Comment by lesserwhirls** [comment] 2015-04-07 14:50
Hi Rich,

Some of these issues seem to be browser specific.

* the grey spinning "working" indicator in the center of the plot never stops spinning

This does not happen in Safari or Firefox, but I do see it happen in Chrome and Opera.

* if you click auto again, you get no plot.

Again, does not happen in Safari/Firefox, but does happen in Chrome/Opera

I'll dig into these, but my initial guess is that it will take quite some time to figure out what the issue is and how it might be fixed. I may need to pass this upstream to the Reading team, although I think they are pushing on ncWms 2.0, which will be in TDS 5.0 (hopefully - we are unofficially shooting for a time frame of June-ish).

However, these two (related) things I see across the board:

* there is no "download in google earth" link
* if you zoom in or change the plot, the "download in google earth" link appears.

For some reason you need to interact with the display window or click "first frame" to get the Google Earth link to appear. This should be somewhat easier to fix as it looks to be an initialization issue when a layer is selected.

**Comment by rsignell-usgs** [comment] 2015-04-07 14:57
@lesserwhirls , thanks so much for the speedy feedback!    We'll try to use Safari or Firefox for demos, and hopefully you guys will find an easy fix to the missing initial "download in google earth" link

**Comment by rsignell-usgs** [comment] 2015-04-07 16:00
@nganju-usgs, just an FYI that the Unidata gang in working on this.

**Comment by lesserwhirls** [comment] 2015-04-07 19:04
Hi Rich,

Would you mind giving

http://threddsrc.ucar.edu/thredds/catalog.html

a spin?

As for the browser specific issues, it looks like it's in the ncWMS layer, as I get the same behavior going through:

http://behemoth.nerc-essc.ac.uk/ncWMS/godiva2.html

We'll have to look to Reading to see what can be done on that front.

**Comment by rsignell-usgs** [comment] 2015-04-07 19:32
Woo hoo!  Lookin' good!  I see the google earth link right from the outset!
![4-7-2015 3-31-46 pm](https://cloud.githubusercontent.com/assets/1872600/7031676/40d875fe-dd3b-11e4-93fb-5cae93d1a5ba.png)

**Closed** 2015-05-31 01:39 UTC

**Comment by jonblower** [comment] 2015-06-29 18:38
Unidata guys - can you let me know if you did anything to the ncWMS/Godiva2 source code to fix this issue? We have had intermittent issues with this kind of thing in different browsers (and different versions of the same browser) but I don't think we tracked down a root cause.
