### ISSUE TITLE
Error reading NetCDF-4 data files with String variable type

### ISSUE THREAD

**Issue by phollemans** [Unidata/thredds#562] opened 2016-06-13 18:31 UTC
When reading these NetCDF-4 files provided by NOAA:

http://www.star.nesdis.noaa.gov/sod/sst/iquam/v2/data.html

I get an error in the 4.6.5 toolsUI GUI about the dataset length.  When I
remove the "platform_id" variable (which is of type String, see attached
dump.cdl file) using ncdump/ncgen, the file can be read with no error.
When I try to read with version 4.5 of the toolsUI GUI, I can open the
file but get an error when reading the "platform_id" variable data.

I've written a test program (Inspect.java attached) which exhibits
the error.  When you comment back in the line that skips reading the
"platform_id" variable, the program runs fine.

Is this a design limitation of the Java NetCDF library?

Peter

[dump.cdl.txt](https://github.com/Unidata/thredds/files/312474/dump.cdl.txt)
[Inspect.java.txt](https://github.com/Unidata/thredds/files/312475/Inspect.java.txt)

**Comment by phollemans** [comment] 2016-06-13 18:41
Here's the error I get in my test program using toolsUI 4.6.5:

Exception in thread "main" java.io.IOException: java.io.EOFException: Reading 201604-STAR-L2i_GHRSST-SST-iQuam-V2.00-v01.0-fv01.0.nc at 59014719 file length = 59014719
	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:427)
	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:748)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:427)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:410)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:395)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:382)
	at Inspect.main(Inspect.java:8)
Caused by: java.io.EOFException: Reading 201604-STAR-L2i_GHRSST-SST-iQuam-V2.00-v01.0-fv01.0.nc at 59014719 file length = 59014719
	at ucar.unidata.io.RandomAccessFile.readFully(RandomAccessFile.java:850)
	at ucar.unidata.io.RandomAccessFile.readFully(RandomAccessFile.java:829)
	at ucar.unidata.io.RandomAccessFile.readString(RandomAccessFile.java:1520)
	at ucar.nc2.iosp.hdf5.H5header.readStringFixedLength(H5header.java:4709)
	at ucar.nc2.iosp.hdf5.H5header.readHeapString(H5header.java:4371)
	at ucar.nc2.iosp.hdf5.H5header.readAttributeData(H5header.java:1050)
	at ucar.nc2.iosp.hdf5.H5header.makeAttribute(H5header.java:946)
	at ucar.nc2.iosp.hdf5.H5header.makeAttributes(H5header.java:922)
	at ucar.nc2.iosp.hdf5.H5header.makeVariable(H5header.java:1398)
	at ucar.nc2.iosp.hdf5.H5header.makeNetcdfGroup(H5header.java:488)
	at ucar.nc2.iosp.hdf5.H5header.read(H5header.java:218)
	at ucar.nc2.iosp.hdf5.H5iosp.open(H5iosp.java:127)
	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1549)
	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:824)
	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:424)
	... 6 more

And using toolsUI 4.5 I get this:

Exception in thread "main" java.lang.IllegalStateException
	at ucar.nc2.iosp.IospHelper.readData(IospHelper.java:396)
	at ucar.nc2.iosp.IospHelper.readDataFill(IospHelper.java:292)
	at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:165)
	at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:143)
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1986)
	at ucar.nc2.Variable.reallyRead(Variable.java:899)
	at ucar.nc2.Variable._read(Variable.java:884)
	at ucar.nc2.Variable.read(Variable.java:695)
	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:557)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:537)
	at ucar.nc2.Variable.read(Variable.java:695)
	at ucar.nc2.Variable.read(Variable.java:641)
	at Inspect.main(Inspect.java:14)

**Comment by lesserwhirls** [comment] 2016-06-15 18:58
@JohnLCaron - anything jump out at you immediately before I try to dig into this one?

**Comment by JohnLCaron** [comment] 2016-06-21 03:23
198109-STAR-L2i_GHRSST-SST-iQuam-V2.00-v01.0-fv01.0.nc

Im reproducing the problem on 5.0. Looks like an attribute of type vlen string.
In readHeapString(), this works until the heapIdAddress = 57542

the heap id looks ok but the heapObject.dataSize is clearly wrong. Funny, all the other heapObjects look fine. Maybe its a damaged file, and we should just skip that attribute. Would be good to see what h5dump has to say. Also, is there a checksum on these files?

closer look shows these problems (next post)

**Comment by JohnLCaron** [comment] 2016-06-21 03:38
float dew_point_temperature(obs=157476);
attribute "valid_max" type vString

has bad heapObject. May be a bug, but....

heres a workaround:

  String readHeapString(long heapIdAddress) throws IOException {
    H5header.HeapIdentifier heapId = new HeapIdentifier(heapIdAddress);
    H5header.GlobalHeap.HeapObject ho = heapId.getHeapObject();
    if (ho == null) throw new IllegalStateException("Cant find Heap Object,heapId="+heapId);
    if (ho.dataSize > 1000 * 1000) return String.format("Bad HeapObject.dataSize=%s", ho);
    raf.seek(ho.dataPos);
    return readStringFixedLength((int) ho.dataSize);
  }

dont see any connection with platform_id.

anyway, what does hdf5 dump say ??

**Comment by phollemans** [comment] 2016-06-21 03:38
I don't see checksum files anywhere on their site.  I did try a few different files though because I thought the same thing, but I got the same error.  Also I can view the data in HDFView and also using the HDF Java API.  So if there's something funny in the files, those software libraries are somehow compensating for it.  I also ran ncdump and it ran OK:

ncdump -v platform_id 201604-STAR-L2i_GHRSST-SST-iQuam-V2.00-v01.0-fv00.0.nc | grep "platform_id =" 
 platform_id = "WCX7445", "WBP3210", "ONCD", "DBLK", "C6RN3", "ZDLP", "PDAN",

It's just the Java NetCDF library that seems to exhibit this issue.

**Comment by JohnLCaron** [comment] 2016-06-21 03:38
also, vlen string on "valid_min" and "valid_max?? that is so wrong.

**Comment by phollemans** [comment] 2016-06-21 03:39
Yes I was going to advise them on various changes, but I am so tired of asking people to change their data format ...

**Comment by JohnLCaron** [comment] 2016-06-21 03:40
hi phollemans:

what does h5dump (or ncdump) say about

float dew_point_temperature(obs=157476);
attribute "valid_max" ??

**Comment by phollemans** [comment] 2016-06-21 03:42
I get this from ncdump:

        float dew_point_temperature(obs) ;
                string dew_point_temperature:long_name = "in situ dew point temperature" ;
                string dew_point_temperature:standard_name = "dew_point_temperature" ;
                string dew_point_temperature:units = "kelvin" ;
                string dew_point_temperature:coordinates = "time lat lon" ;
                string dew_point_temperature:valid_max = "900.0" ;
                string dew_point_temperature:valid_min = "0.0" ;
                dew_point_temperature:_FillValue = -1.f ;
                string dew_point_temperature:source = "Dew point temperature from GTS, ICOADS and IMOS" ;
                string dew_point_temperature:comment = "Available for ships (platform_type = 1), drifting buoys (platform_type = 2), moored buo

**Comment by phollemans** [comment] 2016-06-21 03:43
Yes that's not right at all

**Comment by JohnLCaron** [comment] 2016-06-21 03:45
float dew_point_temperature(obs=157476);
  :long_name = "in situ dew point temperature";
  :standard_name = "dew_point_temperature";
  :units = "kelvin";
  :coordinates = "time lat lon";
  :valid_max = "Bad HeapObject.dataSize=id=16, refCount=0, dataSize=50926081226789702, dataPos=45600";
  :valid_min = "0.0";
  :_FillValue = -1.0f; // float
  :source = "Dew point temperature from GTS, ICOADS and IMOS";
  :comment = "Available for ships (platform_type = 1), drifting buoys (platform_type = 2), moored buoys (platform_type = 3 and 4) and IMOS (platform_type = 7), not available for other platform types";

**Comment by phollemans** [comment] 2016-06-21 03:47
Oh, well that's interesting.

**Comment by JohnLCaron** [comment] 2016-06-21 03:49
One possibility - 4.6.x might still have problems with "large heap" objects thats been fixed in 5.0, that affects platform_id variable (very large heap object makes me think thats possible).

Then, im seeing a different problem that is masked by  platform_id. But, not sure why h5 would have a workaround that would put a reasonable value in "valid_max".

**Comment by JohnLCaron** [comment] 2016-06-21 03:50
Could be some corner case we havent seen before. all the other heap objects seem ok....

**Comment by phollemans** [comment] 2016-06-21 03:54
I don't know if this helps, but h5dump seems OK with it too:

Exex:2016_04_12_iquam_data_files phollema$ h5dump -a /dew_point_temperature/valid_max 201604-STAR-L2i_GHRSST-SST-iQuam-V2.00-v01.0-fv00.0.nc
HDF5 "201604-STAR-L2i_GHRSST-SST-iQuam-V2.00-v01.0-fv00.0.nc" {
ATTRIBUTE "valid_max" {
   DATATYPE  H5T_STRING {
      STRSIZE H5T_VARIABLE;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
   DATA {
   (0): "900.0"
   }
}
}

**Comment by phollemans** [comment] 2016-06-21 03:58
Exex:2016_04_12_iquam_data_files phollema$ h5dump -d /platform_id 201604-STAR-L2i_GHRSST-SST-iQuam-V2.00-v01.0-fv00.0.nc | head -20
HDF5 "201604-STAR-L2i_GHRSST-SST-iQuam-V2.00-v01.0-fv00.0.nc" {
DATASET "/platform_id" {
   DATATYPE  H5T_STRING {
      STRSIZE H5T_VARIABLE;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SIMPLE { ( 545697 ) / ( 545697 ) }
   DATA {
   (0): "WCX7445", "WBP3210", "ONCD", "DBLK", "C6RN3", "ZDLP", "PDAN",
   (7): "ZMFR", "DBBE", "VROC5", "A8ET3", "VRDU9", "BATFR28", "VRJH7",
   (14): "BATFR08", "9V2731", "DJMG2", "9V8207", "BATFR19", "VRVP2", "DNCQ",
   (21): "DDID2", "BATFR36", "C6AX6", "DBBH", "BATFR55", "SJCD", "D5AH6",
   (28): "BATFR59", "CQHR", "ZCDJ9", "KAOU", "KAOU", "WTEE", "VRKK2", "LXGV",
   (36): "VRKJ7", "DCLH2", "ONDY", "VROX8", "VRMU3", "3EPD8", "A8WP6",
   (43): "A8IY2", "9V8208", "CQES", "7JNU", "SHIP", "9VMU5", "DIOY2", "KGSU",
   (51): "CQCU", "A8KC6", "VRFS2", "VRID2", "VRWM2", "A8CB7", "LGWS",
   (58): "S6LT3", "MPMM5", "BATFR45", "H8AC", "VRKB8", "J8PE3", "PCIH",
   (65): "VQGQ4", "C6AX3", "VRCX7", "OWFD2", "BATFR56", "DGXS", "A8ZV7",

**Comment by JohnLCaron** [comment] 2016-06-21 04:13
Ok, i found the problem. An extra object is being read from the Global Heap. Im submitting a pull request, and Unidata will see if it breaks any regression tests. Thanks for reporting, always nice to squash another bug.

**Comment by phollemans** [comment] 2016-06-21 16:39
Nice, good job!

**Comment by cwardgar** [comment] 2016-07-28 21:53
@JohnLCaron This was fixed by #568, yes?

@DennisHeimbigner Is this issue ready to be closed? I see you self-assigned 28 days ago.

**Comment by DennisHeimbigner** [comment] 2016-07-28 22:20
I have no idea wny I took this one. May have confused it with something else.

**Comment by cwardgar** [comment] 2016-07-28 22:52
Okay, I've verified that this was fixed on 5.0 by #568. I've backported the fix to 4.6 in #602. So this is done.

**Closed by cwardgar** 2016-07-28 22:52 UTC
Labels: Area: HDF, Area: IOSP, Type: Bug
