### ISSUE TITLE
ucar.nc2.util.DiskCache2.canWrite returns true for read-only UNC directories

### ISSUE THREAD

**Issue by cofinoa** [Unidata/thredds#141] opened 2015-06-22 17:09 UTC
The ucar.nc2.util.DiskCache2.canWrite method returns true value when shared windows resources (UNC) paths are read-only.

**Comment by cofinoa** [comment] 2015-06-22 17:10
This an well known bug for nio implementation:
https://bugs.openjdk.java.net/browse/JDK-8052010

no solution exists

**Comment by cwardgar** [comment] 2015-06-23 01:03
Hmm, so is there anything to do for this one? I doubt that the old java.io.File methods are any better.

**Comment by cofinoa** [comment] 2015-06-23 07:32
To avoid issues with API guessing if a path is writable, I think is better to test if a tem file can be created and deleted. 
Please, take a look to the pull-request that I have made.

**Comment by cwardgar** [comment] 2015-06-24 02:03
Based on you link, it seems like this issue was fixed in 8u12 or earlier (I can't reproduce it in 8u45). Nonetheless, it's worthwhile for people who are running NetCDF-Java on earlier versions.

I built on your example to check for another couple cases: https://github.com/Unidata/thredds/blob/92a026d03ec3bbfc44dd379874b3380bc0409137/cdm/src/main/java/ucar/nc2/util/DiskCache2.java#L261

Thanks for the contribution!

**Closed by cwardgar** 2015-06-24 02:03 UTC
