### ISSUE TITLE
FileNotFound: catalog.xml

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds#664] opened 2016-10-25 22:55 UTC
@cwardgar  and I found that the TDS 5.0 snapshot version (`20161019.213203-24`) via [Docker](https://github.com/julienchastang/thredds-docker/tree/5.0-SNAPSHOT) is reporting:

`FileNotFound: grib/NCEP/GFS/Global_0p25deg/catalog.xml`

when trying to access the catalog page of a dataset. For example:

[http://unicloud.westus.cloudapp.azure.com/thredds/catalog/grib/NCEP/GFS/Global_0p25deg/catalog.html](http://unicloud.westus.cloudapp.azure.com/thredds/catalog/grib/NCEP/GFS/Global_0p25deg/catalog.html)

though we may go back to 4.6.6 on Azure where this error is not present.

**Comment by lesserwhirls** [comment] 2016-10-25 23:06
what set of catalogs are you using?

**Comment by julienchastang** [comment] 2016-10-25 23:12
Using Unidata/TdsConfig pretty much out-of-the-box. (Was that your question?)

**Comment by lesserwhirls** [comment] 2016-10-25 23:14
Unidata/TdsConfig thredds, or thredds-dev? With 5.0, you will need to use thredds-dev. That said, there are other things in the thredds-dev catalogs that you may not want. We might need to make a new config set for azure.

**Comment by cwardgar** [comment] 2016-10-26 01:15
I fixed the lack of log output in #665. So, if the problem isn't what Sean pointed out, you can grab the [latest build](http://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20161026.011301-32.war) so that we at least have stack traces.

**Comment by julienchastang** [comment] 2016-10-26 14:41
@lesserwhirls thredds and not thredds-dev. @cwardgar I'll also commit the latest snapshot war version in the `Dockerfile`. My aim here is really to ensure there is not a problem with the `Dockerfile` set up for the 5.0-SNAPHOT branch. At this point, I think I'm comfortable providing a 5.0-SNAPSHOT branch of Unidata/thredds-docker since I don't think there are any problems in Dockerland (at least for this specific issue).

**Comment by cwardgar** [comment] 2016-11-03 07:37
@julienchastang Was this issue fixed by using the thredds-dev TdsConfig?

**Comment by julienchastang** [comment] 2016-11-03 14:29
@cwardgar I never tried. (My aim was to prove to myself the problems we were seeing had nothing to do with the Docker setup.) Would you like me to try so we can close this issue? I can do so sometime today hopefully.

**Comment by cwardgar** [comment] 2016-11-03 15:32
Sure, that would be great.

**Comment by julienchastang** [comment] 2016-11-04 16:28
I believe I am still seeing the[ same problem](http://unicloud.westus.cloudapp.azure.com/thredds/catalog/grib/NCEP/GFS/Global_onedeg/catalog.html). Just so we are on the same page, here is what I did: 
- exploded `TdsConfig/threddsDev/config.zip` in to `/usr/local/tomcat/content/thredds`
- restarted the container with `5.0-SNAPSHOT` version (`20161026.011301-32`)

Grabbing contents of `threddsDev/config.zip` and putting them in `/usr/local/tomcat/content/thredds` is the only change I made between `4.6.6` and the `5.0-SNAPHOT`.

(I did not grab the `pqacts` from `threddsDev`, but that should be irrelevant.) Is there anything else I can do to help?

**Comment by cwardgar** [comment] 2016-11-04 22:19
Did you get an error in threddsServlet.log?

**Comment by julienchastang** [comment] 2016-11-11 00:00
After working with the thredds team, we were able to identify  a mismatch between the TDS version (`5.0` snapshot) and TDM version (`4.6`). The consequence of this discrepancy is that grib index files were not being properly generated and therefore the collection appeared empty.  Closing issue since this was a user error problem.

**Closed** 2016-11-11 00:00 UTC
Labels: Area: Client Catalogs, Type: General Question
