### ISSUE TITLE
Group.getAttributes() returns secret attribute

### ISSUE THREAD

**Issue by TomBlock** [Unidata/thredds#948] opened 2017-11-10 11:01 UTC
When requesting attributes from the root-group the secret attribute "_NCProperties" is returned, among the other custom attributes.

We are copying the content of an already existing file to a newly created (to add/modify variables), a code segment copying the root-attributes is like:

`for (Attribute att : rootGroup.getAttributes()) {`
`     System.out.println(att.getFullName());` 
`     newGroup.addAttribute(att);` 
`}`

The console dump is:

_NCProperties
title
institution
contact
... etc

When creating the new file with NetcdfFileWriter.create() an exception is thrown, because setting the "_NCProperties" attribute fails - it already exists.

java.io.IOException: -42 (NetCDF: String match to name in use) on attribute '_NCProperties = "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.10.1"' on global or group attribute

In our opinion, the secret attribute "_NCProperties" should be suppressed in a call to Group.getAttributes(), as also stated in the documentation (http://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html)

**Comment by DennisHeimbigner** [comment] 2017-11-10 18:28
The problem is that clients need to be able to get the value of _NCProperties
(and other hidden) attributes. In the netcdf-c library, as noted, we did this by
allowing the client to ask for these special attributes only by name. Asking by
e.g. attribute id suppressed them. We will probably need to do something
like that here. I suppose a short term solution is to just ignore attempts to
add a special attribute to a file.

**Comment by DennisHeimbigner** [comment] 2017-11-10 20:32
BTW, I am guessing that you are using version 4.6.x and not 5.0.0.
5.0.0 has code to ignore attempts to write such attributes.

**Comment by TomBlock** [comment] 2017-11-11 07:18
Hi Dennis,
you`re right, I forgot to mention:
we are using version 4.6.10 of the java lib, v 4.4.1.1 of netcdf.so and 1.10.1 of hdf5.so

And I agree, the client should explicitely ask for the secret attributes. I have modified our code to suppress copying the _NCProperties attribute - easy enough to overcome the problem.

Tom

**Comment by DennisHeimbigner** [comment] 2017-11-11 19:48
I am adding fixes to both 4.6 and 5.0 to address this problem.
Thanks for catching it.

**Comment by DennisHeimbigner** [comment] 2017-11-13 20:51
Fixed by pull requests:
https://github.com/Unidata/thredds/pull/949
and
https://github.com/Unidata/thredds/pull/952

**Closed by DennisHeimbigner** 2017-11-13 20:51 UTC
